download:
  delay: 10  # delay in seconds between downloads
  cookiefile_path: "/path/to/your/youtube_cookies.txt"

whisper:
  model: "base"  # model size options: base, small, medium, large

directories:
  podcast_audio_dir: "./app/podcast_audio"
  transcriptions_dir: "./app/transcriptions"
