version: "3.8"

services:
  youtube_downloader:
    build:
      context: ./docker/downloaders
      dockerfile: Dockerfile_youtube_downloader
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  audio_converter:
    build:
      context: ./docker/audio_processing
      dockerfile: Dockerfile_audio_converter
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  audio_normalizer:
    build:
      context: ./docker/audio_processing
      dockerfile: Dockerfile_audio_normalizer
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  audio_splitter:
    build:
      context: ./docker/audio_processing
      dockerfile: Dockerfile_audio_splitter
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  audio_trimmer:
    build:
      context: ./docker/audio_processing
      dockerfile: Dockerfile_audio_trimmer
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  transcription_service:
    build:
      context: ./docker/transcription_service
      dockerfile: Dockerfile_main_transcriber
    volumes:
      - ./data:/app/data
    environment:
      PAPERSERVE_API_KEY: ${PAPERSERVE_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Enable GPU if available
    networks:
      - app_network
    restart: always

  text_loader:
    build:
      context: ./docker/text_pipeline
      dockerfile: Dockerfile_text_loader
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  text_segmenter:
    build:
      context: ./docker/text_pipeline
      dockerfile: Dockerfile_text_segmenter
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  text_tokenizer:
    build:
      context: ./docker/text_pipeline
      dockerfile: Dockerfile_text_tokenizer
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  ner_processor:
    build:
      context: ./docker/text_pipeline
      dockerfile: Dockerfile_ner_processor
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  text_saver:
    build:
      context: ./docker/text_pipeline
      dockerfile: Dockerfile_text_saver
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  celery_worker:
    build:
      context: ./docker/celery_worker
      dockerfile: Dockerfile_celery
    depends_on:
      - django_app
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  dask_worker:
    build:
      context: ./docker/dask_worker
      dockerfile: Dockerfile_dask
    depends_on:
      - django_app
    volumes:
      - ./data:/app/data
    networks:
      - app_network
    restart: always

  django_app:
    build:
      context: ./docker/django_app
      dockerfile: Dockerfile_django
    volumes:
      - ./app:/app
    depends_on:
      - db
      - youtube_downloader
      - audio_converter
      - audio_normalizer
      - audio_splitter
      - audio_trimmer
      - transcription_service
      - text_loader
      - text_segmenter
      - text_tokenizer
      - ner_processor
      - text_saver
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/your_db
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    networks:
      - app_network
    ports:
      - "8000:8000"
    restart: always

  reverse_proxy:
    build:
      context: ./docker/reverse_proxy
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_app
    networks:
      - app_network
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
